table FactSales

	measure 'Sales Amount' =
			SUMX (
			    'FactSales',
			    'FactSales'[UnitPrice] * 'FactSales'[OrderQuantity]
			)

	column SalesOrderNumber
		dataType: string
		sourceColumn: SalesOrderNumber

	column CustomerKey
		dataType: int64
		sourceColumn: CustomerKey

	column ProductKey
		dataType: int64
		sourceColumn: ProductKey

	column OrderDateKey
		dataType: int64
		sourceColumn: OrderDateKey

	column OrderQuantity
		dataType: int64
		sourceColumn: OrderQuantity

	column UnitPrice
		dataType: decimal
		sourceColumn: UnitPrice


    partition 'FactSales' = m
        mode: import
        source =
            let
                Source = Sql.Database("None", "None", [Query = "SELECT [SalesOrderNumber] AS [SalesOrderNumber], [CustomerKey] AS [CustomerKey], [ProductKey] AS [ProductKey], [OrderDateKey] AS [OrderDateKey], [OrderQuantity] AS [OrderQuantity], [UnitPrice] AS [UnitPrice] FROM [dbo].[FactSales]", CreateNavigationProperties=false])
            in
                Source
    